version: '3.2'

services:

  php:
    build: .
    ports:
      - "10030:80"
    container_name: laravel-lunch-php
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    links:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    #    volumes:
    #      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel-lunch
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
    ports:
      - "10031:3306"
    container_name: laravel-lunch-mysql
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci

  redis:
    image: redis:7.0
    volumes:
      - ./docker/redis:/data
    ports:
      - "10032:6379"
    container_name: laravel-lunch-redis